#Interpolation of GP environments 
#Imen Bouhlel July 2018

rm(list=ls())

#load packages
packages <- c( 'ggplot2', 'gganimate','ggimage', 'ggthemes', 'fields', 'jsonlite', 'akima', 'reshape2', 'rapport', 'RColorBrewer',  'animation', 'progress')
lapply(packages, require, character.only=TRUE)

#parameters used in environment generation
lambaVec <- c(2, 4, 8) #length scale of RBF kernel component of environments
sigVec<- c(0.01, 0.05) #variance of white noise kernel
expVec <- c(1,2) #exponentiation of rewards once the payoffs have been min-max scaled to range of [0-1]. Thus, exponentiation by a factor of 2, increases the skew between high and low payoffs
numVec <- seq(0, 9) #iteration number used for generating similar environments

#Combination of parameter values
ops <- expand.grid(lambaVec,
                   sigVec, 
                   expVec,
                   numVec)

colnames(ops)<- c('lambda', 'sigma', 'exp', 'num')

#loop through environments
for (c in 1:nrow(ops)){
  #print(c)
  cond  <- ops[c,] #condition
  #simulation parameters
  lambda <- cond$lambda 
  sig <- cond$sigma
  exp <- cond$exp
  num <- cond$num
  
  #load data generated by environmentGenerator.py
  datafile = paste0('environments/lambda_', lambda,'_sigma_',sprintf("%.2f", sig),'_exp_',sprintf("%00o", exp),'.',num,'.json')
  rawData <- fromJSON(datafile, flatten=TRUE)
  df <- data.frame(matrix(as.numeric(unlist(rawData)), ncol=4, byrow=TRUE, dimnames = list(seq(1,length(rawData)), c('x', 'y', 't', 'z')))) #convert to dataframe
  #summary(df)
  
  #plot environment
  p <- ggplot(data=df,  aes(x = x, y = y, frame = t, fill = z)) +geom_raster()
  #p
  ani.options(interval = 0.2) #frame rate
  gganimate(p)
  
  ######################################
  ###########Interpolation#############
  ####################################
  
  
  ############Spatial Interpolation ###############
  #initial environment size
  dynamicEnvironment <- list()
  rangeX <- 25
  rangeY <- 25
  tsteps <- 25
  interpolationFactor <- 4 #from 25 x 25 x 25 fitness landscape to #100 x 100 x 25 (where the last dimension of time is interpolated later)
  
  #LOOP throught tsteps
  for (time in 0:tsteps){
    #subset of dataframe for specific time step
    df_t <- subset(df,t==time)
    #convert to a matrix format
    df_t_matrix <- matrix(df_t$z,nrow = rangeX+1 ,ncol = rangeY+1)
    
    #bilinear interpolation
    bilinear_interpolated_df_t<- bilinear.grid(seq(0,rangeX,length=rangeX+1),seq(0,rangeY,length=rangeY+1),df_t_matrix, 
                                               nx=(rangeX*interpolationFactor)+1,ny=(rangeY*interpolationFactor)+1, 
                                               dx=(1/interpolationFactor), dy=(1/interpolationFactor))
    #store in list
    dynamicEnvironment[[time+1]]<- bilinear_interpolated_df_t$z
  }
  

  #plot single environment
  zmin <- min(bilinear_interpolated_df_t$z, na.rm=TRUE)
  zmax <- max(bilinear_interpolated_df_t$z, na.rm=TRUE)
  breaks <- pretty(c(zmin,zmax),101)
  colors <- heat.colors(length(breaks)-1)
  image(bilinear_interpolated_df_t, breaks=breaks, col=colors)
  #contour(data_to_plot, add=TRUE)
  
  #convert to long format:
  tsteps <- 25
  dynamicEnvironment_df <- data.frame(x = numeric(), y = numeric(), z = numeric(), t = numeric())
  for (time in 0:tsteps){
    data_matrixFormat <- dynamicEnvironment[[time+1]]
    data_longFormat <- melt(data_matrixFormat)
    data_longFormat <- data.frame(data_longFormat)
    colnames(data_longFormat) <- c("x", "y", "z")
    data_longFormat$t <- time
    dynamicEnvironment_df <- rbind(dynamicEnvironment_df, data_longFormat)
  }
  
  
  #plot animated environment
  zmin <- min(dynamicEnvironment_df$z, na.rm=TRUE)
  zmax <- max(dynamicEnvironment_df$z, na.rm=TRUE)
  breaks <- pretty(c(zmin,zmax),101)
  colours <- heat.colors(length(breaks)-1)
  p <- ggplot(data=dynamicEnvironment_df,  aes(x = x, y = y, frame = t, fill = z)) +
    geom_raster()+
    scale_fill_gradientn(colours = heat.colors(length(breaks)-1), breaks = breaks, labels = NULL, name = "Reward" )
  
  ani.options(interval = 0.2)
  gganimate(p)
  #gganimate(p, file="plots/GPenv_spaceinterpolated.gif", fps=10) # Save
  
  
  ############Temporal Interpolation##############
  
  #bilinear interpolation
  new_rangeX <- length(unique(dynamicEnvironment_df$x))
  new_rangeY <- length(unique(dynamicEnvironment_df$y))
  num_totalPoints <- new_rangeX*new_rangeY
  interpolationFactor <- 4
  df_matrix <- matrix(dynamicEnvironment_df$z,nrow = num_totalPoints ,ncol = tsteps+1)
  
  temporally_bilinear_interpolated_df<- bilinear.grid(seq(1,num_totalPoints,length=num_totalPoints),seq(0,tsteps,length=tsteps+1),df_matrix, 
                                                      nx=(num_totalPoints),ny=(tsteps*interpolationFactor), 
                                                      dx=1, dy=(1/interpolationFactor)
  
  #convert to long format:
  new_tsteps <- ncol(temporally_bilinear_interpolated_df$z)
  dynamicEnvironment_df <- data.frame(x = numeric(), y = numeric(), z = numeric(), t = numeric())
  for (time in 1:new_tsteps){
    data_t <- data.frame(matrix(NA, nrow = num_totalPoints, ncol = 4))
    colnames(data_t) <- c("x", "y", "z", "t")
    data_t$t <- time
    data_t$z <- temporally_bilinear_interpolated_df$z[,time]
    data_t$x <- rep(1:new_rangeX, new_rangeY)
    data_t$y <- rep(1:new_rangeY, each=new_rangeX)
    
    dynamicEnvironment_df <- rbind(dynamicEnvironment_df, data_t)
  }
  
  #rescale environment to [-1,1]
  dynamicEnvironment_df$x <- (dynamicEnvironment_df$x - 51)/(50)
  dynamicEnvironment_df$y <- (dynamicEnvironment_df$y - 51)/(50)
  
  
  #plot animated environment
  zmin <- min(dynamicEnvironment_df$z, na.rm=TRUE)
  zmax <- max(dynamicEnvironment_df$z, na.rm=TRUE)
  breaks <- pretty(c(zmin,zmax),101)
  colours <- heat.colors(length(breaks)-1)
  p <- ggplot(data=dynamicEnvironment_df,  aes(x = x, y = y, frame = t, fill = z)) +
    geom_raster()+
    theme_classic()+
    scale_fill_distiller(palette = "Spectral", breaks = breaks, labels = NULL, name = "Reward")
  
  ani.options(interval = 0.1)
  #gganimate(p)
  gganimate(p, file=paste("plots/Environments/GPenv_lambda_",lambda,"_sigma_",sig,"_exp_",exp,".",num,"_fullyInterpolated.gif"), ani.width = 750, ani.height = 700, fps=25) # Save
  #save data
  save(dynamicEnvironment_df, file=paste("data/Environment_lambda_",lambda,"_sigma_",sig,"_exp_",exp,".",num,".Rdata"))
}
